services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_PATH=${DB_PATH}
    volumes:
      - ./app:/workspace/app
      - db-data:/data
    networks:
      - back-net
    healthcheck:
         test: ["CMD", "python3", "-c", "import socket; s = socket.socket(); s.connect(('127.0.0.1', 8000))"]
         interval: 3s
         timeout: 2s
         retries: 3
         start_period: 5s


  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - front-net
      - back-net
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_healthy


networks:
  front-net:
  back-net:


volumes:
  db-data: